### ISSUE TITLE
Media queries problem

### ISSUE THREAD

**Issue by ardsh0ck** [jonathantneal/media-prefers-interface#5]
Hello, I have some construction:

```css
@media (color-index: 48) and (max-width: 767px) {
.element {
    background-color: #141414;
}
}

@media (color-index: 48) and (min-width: 768px) {
.element {
    background-color: yellow;
}
}
```
and last one media query is not working... How can I resolve this?
